### ISSUE TITLE
PI page show false/old/duplicate data about Extracotrs

### ISSUE THREAD

**Issue by H4Z4RD-H42** [eveseat/seat#332]
* **Problem**: _Whats wrong?_
The PI page show false/old/duplicate data about Extracotrs.

* **Expected**: _What did you expect to happen?_
The page should show 1 row for each extractor for each planet

* **Logs / Screenshots / Proof**: _The more information you give the better!_

-- At the beginning the situation was this:
![image](https://user-images.githubusercontent.com/6650832/40312429-253f4f74-5d13-11e8-9470-cf264a246bab.png)

tried to logout and login in seat to update data, but nothing has changed. also giving the command `docker exec -it seat-app php artisan esi: update: character {id}` and receiving the message `Processed 1 refresh tokens` nothing has changed.

-- Some hours later i tried again and the situation was this:
![image](https://user-images.githubusercontent.com/6650832/40311390-e77c70b6-5d0f-11e8-8c5e-a33df733ffb8.png)

-- Next, i restart the extractor for this planet and i see this:
![image](https://user-images.githubusercontent.com/6650832/40312262-a80700ba-5d12-11e8-851b-1584a399a6ee.png)

The images refer always to the same planet that have 2 Extractors installed and 11 heads in total.
It seems like it adds new data every time instead of updating existing data.

* **Version Info**: _PHP Version, SeAT Version, Operating System etc._
SeAT 3.0.0 beta, SeAT Web v3.0.0-beta14, PHP 7.2.5-0ubuntu0.18.04.1

**Comment by warlof** [comment]
@H4Z4RD-H42 not certain it has been addressed. Can you tell me if it's still an open case ?

**Comment by herpaderpaldent** [comment]
![image](https://user-images.githubusercontent.com/6583519/41505918-34bc645e-7213-11e8-8716-9f05a26f03c1.png)
I had the same error and i don't have it anymore on Web 3.0.1

**Comment by H4Z4RD-H42** [comment]
my corp mate still have this issue.
PI table is ok, but Extractors table not. It show duplicate entries.

@herpaderpaldent try to stop/reset some PI jobs and check if seat update it. Thanks.

**Comment by warlof** [comment]
The display issue will be sorted by eveseat/services#57
