### ISSUE TITLE
Error 500 related to mining

### ISSUE THREAD

**Issue by MoucceuWildfire** [eveseat/seat#446]
* **Problem**: People that added many characters that mined a LOT of ore gets ERROR 500 while trying to get in SeAT. Corporation`s mining tab shows the same error 500.
* **Expected**: HTTP ERROR 500
* **Logs / Screenshots / Proof**: Some additional information: those SeAT accounts are still available through link like https://dsons.info/character/list. An people can brows their characters and all tabs work. Only HOME page on which the total cost of the dug ore is calculated is not available. I noted that in the process of adding characters to one of the diggers, the total cost of the dug was a few trillion Isks that is nonsence.
* **Version Info**: Ubuntu 18.04 server full upgraded, SDE Version sde-20180827-TRANQUILITY | Web Version 3.0.8,  SeAT Api 3.0.4, SeAT Console 3.0.2, SeAT Eveapi 3.0.6, SeAT Services 3.0.2
 Nginx outside docker to support https + certbot. Xeon E5450 quad-core + 8 GByte DDR2 + SSD, 20MBit/sec internet connection speed.

**Comment by warlof** [comment]
As for trillions thing, that will be fixed on next patch.

Related to e500 you had, can you attach some logs?

**Comment by TyrHeimdal** [comment]
Unsure if related, but we're experiencing 500 errors on our Corp Mining ledger as well.

From our laravel*.log in storage/logs:
> [2018-10-14 13:54:19] local.ERROR: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'average_price' at row 1 (SQL: insert into `historical_prices` (`type_id`, `date`, `average_price`, `adjusted_price`, `updated_at`, `created_at`) values (16269, 2018-10-14, 1244167.15, 268301.17, 2018-10-14 13:54:19, 2018-10-14 13:54:19)) {"userId":94335556,"exception":"[object] (Illuminate\\Database\\QueryException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'average_price' at row 1 (SQL: insert into `historical_prices` (`type_id`, `date`, `average_price`, `adjusted_price`, `updated_at`, `created_at`) values (16269, 2018-10-14, 1244167.15, 268301.17, 2018-10-14 13:54:19, 2018-10-14 13:54:19)) at /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'average_price' at row 1 at /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:144, PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'average_price' at row 1 at /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142)
> [stacktrace]
> #0 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `hi...', Array, Object(Closure))
> #1 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `hi...', Array, Object(Closure))
> #2 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `hi...', Array)
> #3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2142): Illuminate\\Database\\Connection->insert('insert into `hi...', Array)
> #4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1283): Illuminate\\Database\\Query\\Builder->insert(Array)
> #5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(698): Illuminate\\Database\\Eloquent\\Builder->__call('insert', Array)
> #6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\\Database\\Eloquent\\Model->performInsert(Object(Illuminate\\Database\\Eloquent\\Builder))
> #7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(382): Illuminate\\Database\\Eloquent\\Model->save()
> #8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1038): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}(Object(Seat\\Services\\Models\\HistoricalPrices))
> #9 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(383): tap(Object(Seat\\Services\\Models\\HistoricalPrices), Object(Closure))
> #10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1477): Illuminate\\Database\\Eloquent\\Builder->firstOrCreate(Array, Array)
> #11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1489): Illuminate\\Database\\Eloquent\\Model->__call('firstOrCreate', Array)
> #12 /var/www/seat/vendor/eveseat/services/src/Repositories/Eve/EvePrices.php(52): Illuminate\\Database\\Eloquent\\Model::__callStatic('firstOrCreate', Array)
> #13 /var/www/seat/vendor/eveseat/eveapi/src/Models/Industry/CharacterMining.php(62): Seat\\Eveapi\\Models\\Industry\\CharacterMining->getHistoricalPrice(16269, '2018-10-14')
> #14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(438): Seat\\Eveapi\\Models\\Industry\\CharacterMining->getValueAttribute(NULL)
> #15 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(340): Illuminate\\Database\\Eloquent\\Model->mutateAttribute('value', NULL)
> #16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(313): Illuminate\\Database\\Eloquent\\Model->getAttributeValue('value')
> #17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1405): Illuminate\\Database\\Eloquent\\Model->getAttribute('value')
> #18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Arr.php(148): Illuminate\\Database\\Eloquent\\Model->offsetExists('value')
> #19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/helpers.php(472): Illuminate\\Support\\Arr::exists(Object(Seat\\Eveapi\\Models\\Industry\\CharacterMining), 'value')
> #20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1565): data_get(Object(Seat\\Eveapi\\Models\\Industry\\CharacterMining), Array)
> #21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1460): Illuminate\\Support\\Collection->Illuminate\\Support\\{closure}(Object(Seat\\Eveapi\\Models\\Industry\\CharacterMining))
> #22 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\{closure}(340189713.22, Object(Seat\\Eveapi\\Models\\Industry\\CharacterMining))
> #23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1228): array_reduce(Array, Object(Closure), 0)
> #24 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1461): Illuminate\\Support\\Collection->reduce(Object(Closure), 0)
> #25 /var/www/seat/vendor/eveseat/web/src/Http/Controllers/Corporation/MiningLedgerController.php(63): Illuminate\\Support\\Collection->sum(Object(Closure))
> #26 [internal function]: Seat\\Web\\Http\\Controllers\\Corporation\\MiningLedgerController->Seat\\Web\\Http\\Controllers\\Corporation\\{closure}(Object(Illuminate\\Database\\Eloquent\\Collection), 95508854)
> #27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Support/Collection.php(861): array_map(Object(Closure), Array, Array)
> #28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php(139): Illuminate\\Support\\Collection->map(Object(Closure))
> #29 /var/www/seat/vendor/eveseat/web/src/Http/Controllers/Corporation/MiningLedgerController.php(66): Illuminate\\Database\\Eloquent\\Collection->map(Object(Closure))
> #30 [internal function]: Seat\\Web\\Http\\Controllers\\Corporation\\MiningLedgerController->getLedger(113309599, '2018', '10')
> #31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
> #32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('getLedger', Array)
> #33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Seat\\Web\\Http\\Controllers\\Corporation\\MiningLedgerController), 'getLedger')
> #34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
> #35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
> #36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #37 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Bouncer/CorporationBouncer.php(53): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Seat\\Web\\Http\\Middleware\\Bouncer\\CorporationBouncer->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'mining')
> #39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #40 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Locale.php(44): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Seat\\Web\\Http\\Middleware\\Locale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #43 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Authenticate.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Seat\\Web\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #46 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #47 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #48 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #49 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #50 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #51 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #52 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #53 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #54 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #55 /var/www/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #56 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #57 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #58 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #59 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #60 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #61 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #62 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #63 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #64 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #65 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
> #66 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
> #67 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
> #68 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
> #69 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
> #70 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
> #71 /var/www/seat/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #72 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #73 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #74 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #75 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #76 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #77 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #78 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #79 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #80 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #81 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #82 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #83 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #84 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
> #85 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
> #86 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
> #87 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
> #88 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
> #89 /var/www/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
> #90 {main}

**Comment by warlof** [comment]
@TyrHeimdal it is related to this : https://github.com/eveseat/seat/issues/451 and will be fixed into eveseat/service@3.0.4

**Comment by MoucceuWildfire** [comment]
Since last update i see not error 500 but "Woops..."

**Comment by kwazulueve** [comment]
Getting the same error as Tyr Heimdal atm for people that mined a lot

**Comment by TyrHeimdal** [comment]
> Getting the same error as Tyr Heimdal atm for people that mined a lot

Fixed this thanks to @warlof pointing me in the right direction.

Solution (make sure the path to your SeAT instance is correct!):
- Put your SeAT instance in maintenance mode
`php artisan down`
- Make sure you've updated your instance properly as documented at https://eveseat.github.io/docs/upgrading/general/
- Update SDE by adding the following to your .env file:
```
echo "SDE_VERSION=sde-20181009-TRANQUILITY" >> /var/www/seat/.env
php artisan eve:update:sde
```
- Import the DB migration needed to update the database table scheme:
```
wget https://raw.githubusercontent.com/herpaderpaldent/services/4ef2dfd19af500a08adea5eef0d0f7a69b605150/src/database/migrations/2018_10_05_064533_alter_historical_prices_columns.php -O /var/www/seat/database/migrations/2018_10_05_064533_alter_historical_prices_columns.php
php artisan migrate
```
Take your SeAT instance out of maintenance mode again:
`php artisan up`
Restart supervisord to make sure workers are not running old code:
`supervisorctl restart all`

**Comment by jediefe** [comment]
Proposed bugfix worked for me.

**Comment by MoucceuWildfire** [comment]
But how to fix this issue in docker-based instance? I updated SDE to sde-20181009-TRANQUILITY bit still getting "Whoops" in corp mining ledger. My way was "docker-compose pull" -> "down" -> "up -d"

**Comment by insuusvenerati** [comment]
@MoucceuWildfire cd into your directory containing you docker-compose.yml file. Run
 `docker-compose exec seat-app ash`
Then run the commands like `php artisan down`

**Comment by MoucceuWildfire** [comment]
Well insuusvenerati thanks for advice. In my case these steps didn't help. I`m still getting "Whoops" at corporation "Mining" page and "Home" page is still unavailable for users with huge ore yield. I don't really care but i had to try to fix....
https://cloud.mail.ru/public/EBGN/mnEMSkMCD <- my command line output.

**Comment by insuusvenerati** [comment]
@MoucceuWildfire Right but you didn't post any logs. Your error could refer to anything. Could use laravel logs at the least.

**Comment by MoucceuWildfire** [comment]
(1/1) FatalErrorExceptionMaximum execution time of 30 seconds exceeded
--
in PDOStatement.php line 66

**Comment by herpaderpaldent** [comment]
Guys you are flooding development channel with your support issues. Leave this thread and solve your issues on slack support.
