### ISSUE TITLE
Some contracts get stuck, don't update status correctly

### ISSUE THREAD

**Issue by Nfinished** [eveseat/seat#762]
I've got about nine contracts now that all seem to be permanently marked in_progress/pending, despite having been completed. Only thing I can think of is that they may have been completed past their expiration, would that cause seat to stop updating them?

All packages latest.

**Comment by warlof** [comment]
SeAT isn't applying any logic regarding contract status
If they're not updating, it might be related to an issue fixed by eveseat/eveapi@4.9.2
Or those contract are non longer returned by ESI which prevent them to be updated.

You can force a contract to be updated using `php artisan esi:update:contracts unique_id_from_non_updating_contract`
You can retrieve a contract ID from the cube button showing his detail - it's the last number from the returned link.

**Comment by Nfinished** [comment]
Could it be that ESI isn't returning expired contracts?  Force updating didn't fix the contract's status.

**Comment by warlof** [comment]
Try to find them in esi. But if they're not returned, they will not be updated https://esi.evetech.net/ui/#/Contracts

**Comment by Crypta-Eve** [comment]
If this is still ongoing, please reach out in the SeAT discord.
